
set(ENABLED_GEMS
    ROS2
    ROS2Sensors
    ROS2Controllers
    Playground
    Atom
    AudioSystem
    CameraFramework
    DebugDraw
    DiffuseProbeGrid
    EditorPythonBindings
    EMotionFX
    GameState
    ImGui
    LandscapeCanvas
    LyShine
    MiniAudio
    PhysX5
    PrimitiveAssets
    PrefabBuilder
    SaveData
    ScriptCanvasPhysics
    ScriptEvents
    StartingPointInput
    TextureAtlas
    RemoteTools
)
